2025-09-13 19:18:03.583 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration growatt_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-13 19:18:07.047 INFO (MainThread) [homeassistant.setup] Setting up system_log
2025-09-13 19:18:07.053 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-09-13 19:18:07.127 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.08 seconds
2025-09-13 19:18:07.127 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-09-13 19:18:07.128 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2025-09-13 19:18:07.128 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.08 seconds
2025-09-13 19:18:07.128 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.08 seconds
2025-09-13 19:18:07.128 INFO (MainThread) [homeassistant.setup] Setting up network
2025-09-13 19:18:07.130 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.00 seconds
2025-09-13 19:18:07.130 INFO (MainThread) [homeassistant.bootstrap] Setting up stage frontend: {'frontend'}; already set up: {}
Dependencies: {'repairs', 'onboarding', 'config', 'search', 'api', 'auth', 'diagnostics', 'device_automation', 'file_upload', 'lovelace'}; already set up: {'websocket_api', 'http', 'system_log'}
2025-09-13 19:18:07.131 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-09-13 19:18:07.133 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.00 seconds
2025-09-13 19:18:07.134 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-09-13 19:18:07.137 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.00 seconds
2025-09-13 19:18:07.137 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-09-13 19:18:07.138 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.00 seconds
2025-09-13 19:18:07.139 INFO (MainThread) [homeassistant.setup] Setting up config
2025-09-13 19:18:07.143 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.00 seconds
2025-09-13 19:18:07.143 INFO (MainThread) [homeassistant.setup] Setting up search
2025-09-13 19:18:07.143 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2025-09-13 19:18:07.144 INFO (MainThread) [homeassistant.setup] Setting up api
2025-09-13 19:18:07.145 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.00 seconds
2025-09-13 19:18:07.145 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-09-13 19:18:07.146 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.00 seconds
2025-09-13 19:18:07.147 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-09-13 19:18:07.148 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2025-09-13 19:18:07.148 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-09-13 19:18:07.149 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2025-09-13 19:18:07.150 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-09-13 19:18:07.155 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.01 seconds
2025-09-13 19:18:07.157 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of home-assistant-frontend==20250903.5
2025-09-13 19:18:15.728 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-09-13 19:18:15.732 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.00 seconds
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage recorder: {'recorder'}
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage debugger: {'debugpy'}
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage zeroconf: {'zeroconf'}
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage 1: {'hassio', 'bluetooth', 'cloud', 'mqtt_eventstream', 'dhcp', 'ssdp', 'usb'}
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'shopping_list', 'script', 'scene', 'application_credentials', 'schedule', 'tag', 'automation', 'radio_browser', 'zone', 'hardware', 'input_number', 'input_datetime', 'input_button', 'counter', 'sun', 'system_health', 'input_boolean', 'backup', 'timer', 'analytics', 'person', 'input_select', 'input_text'}; already set up: {'network', 'frontend', 'logger'}
Dependencies: {'blueprint', 'image_upload', 'trace'}; already set up: {'http', 'websocket_api', 'api', 'auth', 'device_automation'}
2025-09-13 19:18:15.733 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-09-13 19:18:15.735 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.00 seconds
2025-09-13 19:18:15.735 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-09-13 19:18:15.736 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.00 seconds
2025-09-13 19:18:15.736 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-09-13 19:18:15.736 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.00 seconds
2025-09-13 19:18:15.736 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-09-13 19:18:15.736 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.00 seconds
2025-09-13 19:18:15.737 INFO (MainThread) [homeassistant.setup] Setting up script
2025-09-13 19:18:15.737 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.00 seconds
2025-09-13 19:18:15.739 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-09-13 19:18:15.740 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-09-13 19:18:15.741 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.00 seconds
2025-09-13 19:18:15.741 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-09-13 19:18:15.742 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.00 seconds
2025-09-13 19:18:15.742 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-09-13 19:18:15.743 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.00 seconds
2025-09-13 19:18:15.744 INFO (MainThread) [homeassistant.setup] Setting up person
2025-09-13 19:18:15.744 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-09-13 19:18:15.745 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.00 seconds
2025-09-13 19:18:15.746 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.00 seconds
2025-09-13 19:18:15.749 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.01 seconds
2025-09-13 19:18:15.750 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2025-09-13 19:18:15.751 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.02 seconds
2025-09-13 19:18:15.751 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of radios==0.3.2
2025-09-13 19:18:15.756 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-09-13 19:18:15.767 INFO (MainThread) [homeassistant.setup] Setting up shopping_list
2025-09-13 19:18:15.768 INFO (MainThread) [homeassistant.setup] Setup of domain shopping_list took 0.00 seconds
2025-09-13 19:18:15.771 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-09-13 19:18:15.772 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.00 seconds
2025-09-13 19:18:15.775 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-09-13 19:18:15.776 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.00 seconds
2025-09-13 19:18:15.778 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-09-13 19:18:15.779 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.00 seconds
2025-09-13 19:18:15.784 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-09-13 19:18:15.786 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.00 seconds
2025-09-13 19:18:15.800 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-09-13 19:18:15.803 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.00 seconds
2025-09-13 19:18:15.805 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-09-13 19:18:15.806 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.00 seconds
2025-09-13 19:18:15.816 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-09-13 19:18:15.819 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-09-13 19:18:15.821 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.00 seconds
2025-09-13 19:18:15.847 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-09-13 19:18:15.849 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.00 seconds
2025-09-13 19:18:15.857 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-09-13 19:18:15.859 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.00 seconds
2025-09-13 19:18:15.860 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.04 seconds
2025-09-13 19:18:15.861 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-09-13 19:18:15.862 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.00 seconds
2025-09-13 19:18:15.864 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-09-13 19:18:15.866 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.00 seconds
2025-09-13 19:18:15.868 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-09-13 19:18:15.868 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.00 seconds
2025-09-13 19:18:15.872 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2025-09-13 19:18:15.872 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.00 seconds
2025-09-13 19:18:15.872 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up sun.binary_sensor
2025-09-13 19:18:15.873 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.sun entity: binary_sensor.sun_solar_rising
2025-09-13 19:18:15.873 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-09-13 19:18:15.873 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.00 seconds
2025-09-13 19:18:15.873 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-09-13 19:18:15.882 INFO (MainThread) [homeassistant.setup] Setting up todo
2025-09-13 19:18:15.884 INFO (MainThread) [homeassistant.setup] Setup of domain todo took 0.00 seconds
2025-09-13 19:18:15.884 INFO (MainThread) [homeassistant.components.todo] Setting up shopping_list.todo
2025-09-13 19:18:17.565 INFO (MainThread) [homeassistant.setup] Setting up radio_browser
2025-09-13 19:18:17.565 INFO (MainThread) [homeassistant.setup] Setup of domain radio_browser took 0.00 seconds
2025-09-13 19:18:17.704 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 14.12s
2025-09-13 19:18:17.705 INFO (MainThread) [homeassistant.core] Starting Home Assistant 2025.9.2
2025-09-13 19:18:17.712 INFO (MainThread) [homeassistant.setup] Setting up event
2025-09-13 19:18:17.712 INFO (MainThread) [homeassistant.components.event] Setting up backup.event
2025-09-13 19:18:17.714 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new event.backup entity: event.backup_automatic_backup
2025-09-13 19:18:17.714 INFO (MainThread) [homeassistant.components.sensor] Setting up backup.sensor
2025-09-13 19:18:17.714 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.backup entity: sensor.backup_backup_manager_state
2025-09-13 19:18:17.715 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.backup entity: sensor.backup_next_scheduled_automatic_backup
2025-09-13 19:18:17.715 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.backup entity: sensor.backup_last_successful_automatic_backup
2025-09-13 19:18:17.715 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.backup entity: sensor.backup_last_attempted_automatic_backup
2025-09-13 19:18:29.925 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140432561088096] Received unknown command: recorder/info
2025-09-13 19:18:29.984 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432561088096] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:18:51.208 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432561094176] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:18:51.224 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140432561094176] Received unknown command: recorder/info
2025-09-13 19:18:59.106 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967104] Received unknown command: recorder/info
2025-09-13 19:18:59.147 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967104] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:20:00.344 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967104] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:20:00.756 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967104] Received unknown command: recorder/info
2025-09-13 19:20:00.784 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967104] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:21:01.962 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967424] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
2025-09-13 19:21:02.428 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967424] Received unknown command: recorder/info
2025-09-13 19:21:02.467 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140432550967424] Error handling message: Unknown error (unknown_error) Test from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0)
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 578, in handle_get_services
    payload = await _async_get_all_service_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 559, in _async_get_all_service_descriptions_json
    descriptions = await async_get_all_service_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 588, in async_get_all_descriptions
    loaded = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 523, in _load_services_files
    integration.domain: _load_services_file(hass, integration)
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 500, in _load_services_file
    _SERVICES_SCHEMA(
    ~~~~~~~~~~~~~~~~^
        load_yaml_dict(str(integration.file_path / "services.yaml"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 309, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 330, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 590, in validate_sequence
    cval = validate(index_path, value)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.13/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 164, in validate_supported_feature
    return _validate_option_or_feature(supported_feature, "supported feature")
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 139, in _validate_option_or_feature
    base_components = _base_components()
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 85, in _base_components
    from homeassistant.components import (  # noqa: PLC0415
    ...<19 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/__init__.py", line 38, in <module>
    from .entity import AITaskEntity
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/ai_task/entity.py", line 9, in <module>
    from homeassistant.components.conversation import (
    ...<3 lines>...
    )
  File "/home/vscode/.local/lib/python3.13/site-packages/homeassistant/components/conversation/__init__.py", line 9, in <module>
    from hassil.recognize import RecognizeResult
ModuleNotFoundError: No module named 'hassil'
[dev-start] Starting Home Assistant...
2025-09-13 20:08:22.132 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration growatt_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-13 20:08:26.768 INFO (MainThread) [homeassistant.setup] Setting up system_log
2025-09-13 20:08:26.777 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-09-13 20:08:26.883 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.12 seconds
2025-09-13 20:08:26.883 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.12 seconds
2025-09-13 20:08:26.883 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.12 seconds
2025-09-13 20:08:26.883 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-09-13 20:08:26.884 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2025-09-13 20:08:26.884 INFO (MainThread) [homeassistant.setup] Setting up network
2025-09-13 20:08:26.885 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.00 seconds
2025-09-13 20:08:26.885 INFO (MainThread) [homeassistant.bootstrap] Setting up stage frontend: {'frontend'}; already set up: {}
Dependencies: {'auth', 'file_upload', 'lovelace', 'search', 'config', 'device_automation', 'api', 'diagnostics', 'onboarding', 'repairs'}; already set up: {'system_log', 'http', 'websocket_api'}
2025-09-13 20:08:26.885 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-09-13 20:08:26.886 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.00 seconds
2025-09-13 20:08:26.887 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-09-13 20:08:26.887 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2025-09-13 20:08:26.887 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-09-13 20:08:26.887 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.00 seconds
2025-09-13 20:08:26.887 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-09-13 20:08:26.888 INFO (MainThread) [homeassistant.setup] Setting up search
2025-09-13 20:08:26.888 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2025-09-13 20:08:26.889 INFO (MainThread) [homeassistant.setup] Setting up config
2025-09-13 20:08:26.893 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.00 seconds
2025-09-13 20:08:26.893 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-09-13 20:08:26.894 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2025-09-13 20:08:26.895 INFO (MainThread) [homeassistant.setup] Setting up api
2025-09-13 20:08:26.901 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.01 seconds
2025-09-13 20:08:26.902 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-09-13 20:08:26.903 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.00 seconds
2025-09-13 20:08:26.903 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-09-13 20:08:26.905 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.00 seconds
2025-09-13 20:08:26.909 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.02 seconds
2025-09-13 20:08:26.910 INFO (SyncWorker_4) [homeassistant.util.package] Attempting install of home-assistant-frontend==20250903.5
2025-09-13 20:08:35.394 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.00 seconds
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage recorder: {'recorder'}
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage debugger: {'debugpy'}
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage zeroconf: {'zeroconf'}
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage 1: {'cloud', 'hassio', 'usb', 'mqtt_eventstream', 'bluetooth', 'ssdp', 'dhcp'}
2025-09-13 20:08:35.400 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'shopping_list', 'radio_browser', 'timer', 'schedule', 'person', 'input_number', 'system_health', 'input_boolean', 'script', 'input_datetime', 'hardware', 'counter', 'analytics', 'automation', 'input_text', 'tag', 'zone', 'input_button', 'scene', 'backup', 'input_select', 'sun', 'application_credentials'}; already set up: {'frontend', 'network', 'logger'}
Dependencies: {'blueprint', 'image_upload', 'trace'}; already set up: {'auth', 'http', 'device_automation', 'websocket_api', 'api'}
2025-09-13 20:08:35.401 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-09-13 20:08:35.403 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.00 seconds
2025-09-13 20:08:35.403 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-09-13 20:08:35.403 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.00 seconds
2025-09-13 20:08:35.403 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-09-13 20:08:35.403 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.00 seconds
2025-09-13 20:08:35.404 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-09-13 20:08:35.404 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.00 seconds
2025-09-13 20:08:35.407 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-09-13 20:08:35.409 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.00 seconds
2025-09-13 20:08:35.409 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-09-13 20:08:35.411 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.00 seconds
2025-09-13 20:08:35.412 INFO (MainThread) [homeassistant.setup] Setting up person
2025-09-13 20:08:35.412 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-09-13 20:08:35.414 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.00 seconds
2025-09-13 20:08:35.415 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-09-13 20:08:35.415 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.00 seconds
2025-09-13 20:08:35.415 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-09-13 20:08:35.416 INFO (MainThread) [homeassistant.setup] Setting up script
2025-09-13 20:08:35.416 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.00 seconds
2025-09-13 20:08:35.419 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.01 seconds
2025-09-13 20:08:35.420 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2025-09-13 20:08:35.421 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.02 seconds
2025-09-13 20:08:35.422 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.01 seconds
2025-09-13 20:08:35.424 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-09-13 20:08:35.430 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of radios==0.3.2
2025-09-13 20:08:35.439 INFO (MainThread) [homeassistant.setup] Setting up shopping_list
2025-09-13 20:08:35.439 INFO (MainThread) [homeassistant.setup] Setup of domain shopping_list took 0.00 seconds
2025-09-13 20:08:35.443 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-09-13 20:08:35.444 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.00 seconds
2025-09-13 20:08:35.451 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-09-13 20:08:35.453 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.00 seconds
2025-09-13 20:08:35.458 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-09-13 20:08:35.459 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.00 seconds
2025-09-13 20:08:35.463 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-09-13 20:08:35.464 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.00 seconds
2025-09-13 20:08:35.469 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-09-13 20:08:35.470 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.00 seconds
2025-09-13 20:08:35.479 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-09-13 20:08:35.481 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.00 seconds
2025-09-13 20:08:35.483 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-09-13 20:08:35.484 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.00 seconds
2025-09-13 20:08:35.488 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-09-13 20:08:35.489 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.00 seconds
2025-09-13 20:08:35.492 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-09-13 20:08:35.498 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.01 seconds
2025-09-13 20:08:35.505 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-09-13 20:08:35.508 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-09-13 20:08:35.508 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.00 seconds
2025-09-13 20:08:35.511 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2025-09-13 20:08:35.512 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.00 seconds
2025-09-13 20:08:35.512 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up sun.binary_sensor
2025-09-13 20:08:35.513 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-09-13 20:08:35.513 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.00 seconds
2025-09-13 20:08:35.514 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-09-13 20:08:35.519 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-09-13 20:08:35.520 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.00 seconds
2025-09-13 20:08:35.545 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.04 seconds
2025-09-13 20:08:35.554 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-09-13 20:08:35.556 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.00 seconds
2025-09-13 20:08:35.566 INFO (MainThread) [homeassistant.setup] Setting up todo
2025-09-13 20:08:35.570 INFO (MainThread) [homeassistant.setup] Setup of domain todo took 0.00 seconds
2025-09-13 20:08:35.570 INFO (MainThread) [homeassistant.components.todo] Setting up shopping_list.todo
2025-09-13 20:08:35.577 INFO (MainThread) [homeassistant.setup] Setting up event
2025-09-13 20:08:35.578 INFO (MainThread) [homeassistant.setup] Setup of domain event took 0.00 seconds
2025-09-13 20:08:35.578 INFO (MainThread) [homeassistant.components.event] Setting up backup.event
2025-09-13 20:08:35.579 INFO (MainThread) [homeassistant.components.sensor] Setting up backup.sensor
2025-09-13 20:08:37.042 INFO (MainThread) [homeassistant.setup] Setting up radio_browser
2025-09-13 20:08:37.042 INFO (MainThread) [homeassistant.setup] Setup of domain radio_browser took 0.00 seconds
2025-09-13 20:08:37.126 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 14.99s
2025-09-13 20:08:37.126 INFO (MainThread) [homeassistant.core] Starting Home Assistant 2025.9.2
